name: Next.JS Staging CI

on:
  push:
    branches:
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3

      - name: Create .env File
        run: |
          touch .env
          echo DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" >> .env
          echo POSTGRES_CONN_URI="${{ secrets.POSTGRES_CONN_URI }}" >> .env
          echo SESSION_SECRET="${{ secrets.SESSION_SECRET }}" >> .env
          echo BASE_URL="${{ vars.BASE_URL }}" >> .env
          echo NODE_ENV="production" >> .env

      - name: Upload to Server
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: ""
          EXCLUDE: "/.next/, /node_modules/, /.git/, /.github/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            cd ${{ secrets.REMOTE_TARGET }}
            sudo docker compose up --build -d
